"""Exclusion rules applied below the agent, never above it. See
docs/design.md §5.2 — an agent that can see package-lock.json will
eventually spend a call on it; one that cannot, cannot.

Used by both the survey (zero-token pass) and the live tools
(list_directory / read_file / search_repo), so a path excluded during
survey is never later surfaced by a tool either.
"""

from __future__ import annotations

import fnmatch
import re

# Directories pruned entirely — nothing beneath them is ever walked.
EXCLUDED_DIR_NAMES: frozenset[str] = frozenset(
    {
        ".git",
        "node_modules",
        "vendor",
        ".venv",
        "venv",
        "env",
        "dist",
        "build",
        "target",
        ".next",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        ".tox",
        "site-packages",
        "__snapshots__",
        ".egg-info",
        "coverage",
        ".idea",
        ".vscode",
        ".terraform",
    }
)

# Filename globs excluded regardless of directory.
EXCLUDED_FILE_GLOBS: tuple[str, ...] = (
    # lock files
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "Cargo.lock",
    "Gemfile.lock",
    "composer.lock",
    "uv.lock",
    # generated code by naming convention
    "*_pb2.py",
    "*_pb2_grpc.py",
    "*.pb.go",
    "*.g.dart",
    "*.generated.*",
    # minified / bundled
    "*.min.js",
    "*.min.css",
    "*.bundle.js",
    "*.bundle.css",
    "*.map",
    # snapshots / golden files
    "*.snap",
    # OS/editor noise
    ".DS_Store",
)

# Extensions treated as binary/media — excluded from text reads outright.
BINARY_EXTENSIONS: frozenset[str] = frozenset(
    {
        ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".svg", ".webp",
        ".mp3", ".mp4", ".mov", ".avi", ".webm", ".wav",
        ".zip", ".tar", ".gz", ".bz2", ".7z", ".rar",
        ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
        ".so", ".dylib", ".dll", ".exe", ".bin", ".a", ".o",
        ".class", ".jar", ".war",
        ".woff", ".woff2", ".ttf", ".eot", ".otf",
        ".pyc", ".pyo",
        ".db", ".sqlite", ".sqlite3",
    }
)

# First-line markers that identify machine-generated source. Checked only
# against a small prefix of a candidate file's content, never the whole file.
_GENERATED_RE = re.compile(
    r"generated by|do not edit|@generated|autogenerated|auto-generated",
    re.IGNORECASE,
)


def is_excluded_dir(name: str) -> bool:
    return name in EXCLUDED_DIR_NAMES or name.endswith(".egg-info")


def is_excluded_file(name: str) -> bool:
    if any(fnmatch.fnmatch(name, pattern) for pattern in EXCLUDED_FILE_GLOBS):
        return True
    return is_binary_extension(name)


def is_binary_extension(name: str) -> bool:
    for ext in BINARY_EXTENSIONS:
        if name.endswith(ext):
            return True
    return False


def looks_generated(head: str) -> bool:
    """head: the first ~5 lines of a candidate file's content."""
    return bool(_GENERATED_RE.search(head))
